# Generated by Django 3.2.15 on 2022-09-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(null=True, upload_to='profilepics')),
                ('employee_name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
